name: Github Actions Demo
on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
 
 
jobs:
    build:
        ## ...
        runs-on: ubuntu-latest
        steps: 
        
        - name: check out the repo
          uses: actions/checkout@v3
          
        - name: build the docker image
          run: docker build . --file ./Dockerfile --tag inline_scanner_test:v1.0
          
        - name: lw-scanner
          run: |
            curl -L https://github.com/lacework/lacework-vulnerability-scanner/releases/download/v0.11.2/lw-scanner-linux-amd64 -o lw-scanner
            chmod +x lw-scanner
            ./lw-scanner image evaluate inline_scanner_test v1.0
          env:
            LW_ACCOUNT_NAME: ${{ secrets.LW_ACCOUNT_NAME }}
            LW_ACCESS_TOKEN: ${{ secrets.LW_ACCESS_TOKEN }}
            
